spring:
  application:
    name: nexarank-click-consumer

  elasticsearch:
    uris: ${ES_URI:https://searchx-es-http.elasticsearch.svc.cluster.local:9200}
    username: ${ES_USERNAME:elastic}
    password: ${ES_PASSWORD:changeme}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:searchx-kafka-dual-role-0.searchx-kafka-kafka-brokers.kafka.svc.cluster.local:9092}

nexarank:
  store: elasticsearch
  kafka:
    topic: search-clicks
    group-id: click-consumer-group

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.nexarank: INFO
    org.springframework.kafka: WARN
